development:
  giphy:
    base_uri: 'http://api.giphy.com/'
    random_uri: 'v1/gifs/random'
    api_key: '<%= ENV["API_GIPHY_KEY"] %>'
  telegram_bot:
    api_key: '<%= ENV["API_TELEGRAM_KEY"] %>'
    chat_id: '<%= ENV["CHAT_ID"] %>'
