development:
  secret_key_base: '<%= ENV["SECRET_KEY_BASE"] %>'
  giphy:
    base_uri: 'http://api.giphy.com/'
    random_uri: 'v1/gifs/random'
    api_key: '<%= ENV["API_GIPHY_KEY"] %>'
  telegram_bot:
    api_key: ''<%= ENV["API_TELEGRAM_KEY"] %>'
